version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=hw02
      - DB_USER=postgres
      - DB_PASSWORD=567234
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: ["python", "main.py"]

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
